services: # Определение сервисов
  redis: # Сервис Redis для работы с данными
    image: redis # Использование последнего (latest) обрза Redis
  app: # Основное приложение
    restart: on-failure # Перезапуск только при ошибках
    build: ./app # Сборка образа из Dockerfile из каталога ./app
    hostname: app # Задает внутреннее имя хоста для контейнера
    depends_on: # Обредеделение зависимостей
    - redis # Запускается после сервиса redis
  nginx: # Nginx в качестве обратного прокси-сервера
    build: ./nginx # Сборка образа из Dockerfile из каталога ./nginx
    ports: # Определение портов для сервиса
    - '80:80' # Пробрасывает порт 80 хоста на 80 порт контейнера
    depends_on: # Обредеделение зависимостей
    - app # Запускается после сервиса app
